// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UepaMed.Infrastructure.Data;

#nullable disable

namespace UepaMed.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824193509_CriarTabelaConviteRevisao")]
    partial class CriarTabelaConviteRevisao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UepaMed.Domain.Entities.ArquivoImportacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataImportacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuantidadeArtigos")
                        .HasColumnType("integer");

                    b.Property<int>("RevisaoId")
                        .HasColumnType("integer");

                    b.Property<int>("TipoArquivo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RevisaoId");

                    b.ToTable("ArquivosImportacao");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Artigo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnoPublicacao")
                        .HasColumnType("integer");

                    b.Property<int>("ArquivoImportacaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Autores")
                        .HasColumnType("text");

                    b.Property<string>("DOI")
                        .HasColumnType("text");

                    b.Property<string>("PMID")
                        .HasColumnType("text");

                    b.Property<string>("Resumo")
                        .HasColumnType("text");

                    b.Property<int>("RevisaoId")
                        .HasColumnType("integer");

                    b.Property<string>("Revista")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArquivoImportacaoId");

                    b.HasIndex("RevisaoId");

                    b.ToTable("Artigos");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.ConviteRevisao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConvidadoPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RespondidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RevisaoId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioConvidadoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConvidadoPorUsuarioId");

                    b.HasIndex("UsuarioConvidadoId");

                    b.HasIndex("RevisaoId", "UsuarioConvidadoId", "Status");

                    b.ToTable("ConvitesRevisao");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Revisao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("Dominio")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Revisoes");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.RevisaoMembro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Papel")
                        .HasColumnType("integer");

                    b.Property<int>("RevisaoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RevisaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RevisoesMembro");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.ArquivoImportacao", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Revisao", "Revisao")
                        .WithMany()
                        .HasForeignKey("RevisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revisao");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Artigo", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.ArquivoImportacao", "ArquivoImportacao")
                        .WithMany("Artigos")
                        .HasForeignKey("ArquivoImportacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UepaMed.Domain.Entities.Revisao", "Revisao")
                        .WithMany()
                        .HasForeignKey("RevisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArquivoImportacao");

                    b.Navigation("Revisao");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.ConviteRevisao", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Usuario", "ConvidadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("ConvidadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UepaMed.Domain.Entities.Revisao", "Revisao")
                        .WithMany()
                        .HasForeignKey("RevisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UepaMed.Domain.Entities.Usuario", "UsuarioConvidado")
                        .WithMany()
                        .HasForeignKey("UsuarioConvidadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConvidadoPorUsuario");

                    b.Navigation("Revisao");

                    b.Navigation("UsuarioConvidado");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.Revisao", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.RevisaoMembro", b =>
                {
                    b.HasOne("UepaMed.Domain.Entities.Revisao", "Revisao")
                        .WithMany()
                        .HasForeignKey("RevisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UepaMed.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Revisao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("UepaMed.Domain.Entities.ArquivoImportacao", b =>
                {
                    b.Navigation("Artigos");
                });
#pragma warning restore 612, 618
        }
    }
}
